### ISSUE TITLE
Labels don't show up in BrainTree settings

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction-braintree#16]
<img width="419" alt="dashboard" src="https://cloud.githubusercontent.com/assets/72819/13769584/a6260366-eabb-11e5-8ef0-ea8ffd10191f.png">

**Comment by aaronjudd** [comment]
guessing it's missing i18n labels..?

**Comment by OrganicChem** [comment]
And another:

![screenshot 2016-03-15 at 8 51 03 am](https://cloud.githubusercontent.com/assets/3411037/13778291/608e3a92-ea8b-11e5-9868-9e1f83d554c8.png)

**Comment by zenweasel** [comment]
@OrganicChem that's unrelated to the braintree package so we should open up an issue on reaction.
