### ISSUE TITLE
Does not work with a brand new reaction

### ISSUE THREAD

**Issue by temsa** [reactioncommerce/reaction-braintree#8]
I've cloned the reaction repository, gone to master, run it a first time, then uncommented your package in `.meteor/package` and I get this :

```
Errors prevented startup:

   While selecting package versions:
   error: Conflict: Constraint less@1.0.11 is not satisfied by less 2.5.0_3.
   Constraints on package "less":
   * less@=2.5.0_3 <- top level
   * less@2.5.0_1 <- reactioncommerce:core 0.9.2
   * less@2.5.0_1 <- reactioncommerce:bootstrap-theme 1.7.0
   * less@2.5.0_1 <- reactioncommerce:reaction-accounts 1.5.1
   * less@2.5.0_1 <- reactioncommerce:reaction-shipping 0.6.1
   * less@2.5.0_1 <- reactioncommerce:reaction-analytics 1.1.1
   * less@2.5.0_1 <- reactioncommerce:reaction-social 0.4.1
   * less@1.0.11 <- reactioncommerce:reaction-braintree 1.3.0
```

I've found no reference to this `less` version in your package, so I don't know yet how to fix the issue by myself. Any fix / clue ?

**Comment by temsa** [comment]
@aaronjudd ?

**Comment by aaronjudd** [comment]
See: https://github.com/reactioncommerce/reaction-braintree/issues/6

We have an open issue to upgrade this to compatible with the latest releases.  It shouldn't be a hard upgrade, but we wanted to get tests running for stripe and paypal, before we upgrade this, so we can add tests to this package as well.

**Comment by aaronjudd** [comment]
beginning to work on this for next release. Closing in favor of #6
